chicago_taxi_weather:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: chicago-taxi-weather
      dataset: ctw
      keyfile: /home/carleondel/.gcp/chicago-taxi-weather-661d0d5aea6a.json
      threads: 1
      timeout_seconds: 300
      location: us-central1
